# Generated by Django 2.0 on 2018-01-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_content', models.TextField(max_length=200, verbose_name='评论内容')),
            ],
            options={
                'ordering': ('comment_date',),
            },
        ),
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('image', models.ImageField(upload_to='../statics/images/', verbose_name='封面')),
                ('direct', models.CharField(max_length=20, verbose_name='导演')),
                ('actors', models.CharField(max_length=100, verbose_name='演员')),
                ('pub_date', models.DateTimeField(verbose_name='上映时间')),
                ('hits', models.IntegerField(verbose_name='点击数')),
                ('country', models.ManyToManyField(related_name='movies_country', to='duban.Countrys')),
            ],
            options={
                'ordering': ('hits',),
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=15, verbose_name='电影类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('user_mobile_number', models.CharField(max_length=11, verbose_name='用户手机号')),
                ('user_email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('user_password', models.CharField(max_length=10, verbose_name='用户密码')),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='style',
            field=models.ManyToManyField(related_name='movies_style', to='duban.Styles'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_movies', to='duban.Movies'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_users', to='duban.User'),
        ),
    ]
