# Generated by Django 2.0 on 2018-01-10 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
