# Generated by Django 2.0 on 2018-01-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(related_name='movies_actors', to='DouBan.Actors'),
        ),
    ]
