# Generated by Django 2.0 on 2018-01-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0003_auto_20180110_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='actors',
            field=models.CharField(max_length=50, unique=True, verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='countrys',
            name='country_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='styles',
            name='style',
            field=models.CharField(max_length=15, unique=True, verbose_name='电影类型'),
        ),
    ]
