# Generated by Django 2.0 on 2018-01-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0004_auto_20180110_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(max_length=400, verbose_name='评论内容'),
        ),
    ]
