# Generated by Django 2.0 on 2018-01-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0006_movies_movie_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='direct',
            new_name='director',
        ),
    ]
