# Generated by Django 2.0 on 2018-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0007_auto_20180111_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='actors',
            new_name='movie_actors',
        ),
        migrations.AlterField(
            model_name='movies',
            name='hits',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
