# Generated by Django 2.0 on 2018-01-17 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.CharField(max_length=50, unique=True, verbose_name='演员')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_content', models.TextField(max_length=400, verbose_name='评论内容')),
            ],
            options={
                'ordering': ('comment_date',),
            },
        ),
        migrations.CreateModel(
            name='Countrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, unique=True, verbose_name='国家')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('image', models.ImageField(upload_to='static/images/', verbose_name='封面')),
                ('director', models.CharField(max_length=20, verbose_name='导演')),
                ('pub_date', models.DateField(verbose_name='上映时间')),
                ('hits', models.IntegerField(default=0, verbose_name='点击数')),
                ('country', models.ManyToManyField(related_name='movies_country', to='DouBan.Countrys')),
                ('movie_actors', models.ManyToManyField(related_name='movies_actors', to='DouBan.Actors')),
            ],
            options={
                'ordering': ('hits',),
            },
        ),
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=15, unique=True, verbose_name='电影类型')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('avatar', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('access_token', models.CharField(blank=True, max_length=100)),
                ('refresh_token', models.CharField(blank=True, max_length=100)),
                ('expires_in', models.BigIntegerField(default=0, max_length=100)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='movies',
            name='style',
            field=models.ManyToManyField(related_name='movies_style', to='DouBan.Styles'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_movies', to='DouBan.Movies'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
