# Generated by Django 2.0 on 2018-01-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires_in',
            field=models.BigIntegerField(default=0),
        ),
    ]
