# Generated by Django 2.0 on 2018-01-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0002_auto_20180117_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='comments',
            field=models.URLField(null=True),
        ),
    ]
