# Generated by Django 2.0 on 2018-01-17 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DouBan', '0003_movies_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
